### ISSUE TITLE
Opened the stream, starting to publish but no image output

### ISSUE THREAD

**Issue by stephennacion06** [ros-drivers/video_stream_opencv#101]
![image](https://user-images.githubusercontent.com/32524849/115986772-6c1e8c80-a5e4-11eb-8d1c-72f093311875.png)

**Comment by awesomebytes** [comment]
There's no much I can do without any further info on what you've tried. Did you check there is anything in the topic?
I don't see the image_view window either.

There are no errors, so everything seems fine.

**Comment by stephennacion06** [comment]
Yah It's working now. The error only happens when I run first the Hector SLAM package. Thanks for the reply
