### ISSUE TITLE
Change jpeg quality

### ISSUE THREAD

**Issue by JeremieBourque1** [ros-drivers/video_stream_opencv#108]
Hi,

Is there a way to change the jpeg quality for the compressed image topic? By default it is set to 80 but I don't see a parameter for changing it.

Thank you

**Comment by awesomebytes** [comment]
Yeah, you can use dynamic reconfigure to change the compression level from
the compressed image_transport plugin:

http://wiki.ros.org/image_transport/Tutorials/ExaminingImagePublisherSubscriber

**Comment by JeremieBourque1** [comment]
Thank you
