### ISSUE TITLE
Node keeps sending last frame of file

### ISSUE THREAD

**Issue by filipetrocadoferreira** [ros-drivers/video_stream_opencv#23]
In case of reading a video file, the node keeps sending the last frame when it reaches the end of the file.
Is this the desired behavior? 

I can send a PR with the fix

**Comment by awesomebytes** [comment]
Now if we reach the end of the file the program just finishes:
https://github.com/ros-drivers/video_stream_opencv/commit/9091df4ef082063a29bfe345dd36d25a9f8ab935
