### ISSUE TITLE
Publish stereo cameras or video files

### ISSUE THREAD

**Issue by joejevons1001** [ros-drivers/video_stream_opencv#28]
Hello, 

I am new with ROS. I am using this package to publish video files as image topic to ROS and it works really well.

I just wonder, is it possible to publish stereo video files (synchronized) with this package? As I have two seperate video files from left and right cameras.

Thanks!

**Comment by awesomebytes** [comment]
There is nothing implemented for that unfortunately.

I'd record both topics in a rosbag and then using the Python rosbag API I'd
rewrite the timestamps of the second topic to have the same time than the
first....

Or fork the code of this repo to open the two files and grab a frame from
each each time.

Both options may work, one may be more suited to you given your expertise
either in C++ or Python than the other.

Good luck :) let me know if I can help any further.

**Comment by joejevons1001** [comment]
> There is nothing implemented for that unfortunately. I'd record both topics in a rosbag and then using the Python rosbag API I'd rewrite the timestamps of the second topic to have the same time than the first.... Or fork the code of this repo to open the two files and grab a frame from each each time. Both options may work, one may be more suited to you given your expertise either in C++ or Python than the other. Good luck :) let me know if I can help any further.
> […](#)

Thank you so much for the advice! I would try with the first rosbag option.

**Comment by yin-chao** [comment]
> Hello,
> 
> I am new with ROS. I am using this package to publish video files as image topic to ROS and it works really well.
> 
> I just wonder, is it possible to publish stereo video files (synchronized) with this package? As I have two seperate video files from left and right cameras.
> 
> Thanks!

Hello,
Did you resolve it? I have the same question as you.
I will appreciate it if there is any suggestion.

**Comment by sarankhaliq** [comment]
> Hello,
> 
> I am new with ROS. I am using this package to publish video files as image topic to ROS and it works really well.
> 
> I just wonder, is it possible to publish stereo video files (synchronized) with this package? As I have two seperate video files from left and right cameras.
> 
> Thanks!

Will You please guide me, How you published video file? I have successfully build the package, i am not getting how to use it
