### ISSUE TITLE
Could not capture frame video_file.launch

### ISSUE THREAD

**Issue by HareshMiriyala** [ros-drivers/video_stream_opencv#41]
I'm able to play a video.avi file using roslanch video_stream_opencv video_file.launch  

However, it doesn't loop the video though the argument loop_videofile is set to true.

**Comment by HareshMiriyala** [comment]
Just checked that when i convert the .avi file to .mp4, it works !

**Comment by furushchev** [comment]
@HareshMiriyala Hi, thanks for the report!
For debugging, could you paste all the logs displayed in the terminal you run the node using .avi.

**Comment by HareshMiriyala** [comment]
Hi, i donot have access to the project right now. I'm closing this issue for now. For someone looking here for solutions, I was able to fix this problem by having a .mp4 version of the video. Maybe it was a codec issue that it didn't work with the .avi format, but i'm not sure.
