### ISSUE TITLE
Feature Request: switch between UDP and TCP Mode

### ISSUE THREAD

**Issue by majorx234** [ros-drivers/video_stream_opencv#86]
Rtsp streams are also possible over udp.
I've found just a workarround to set ENV-Variable:
`export OPENCV_FFMPEG_CAPTURE_OPTIONS="rtsp_transport;udp"`
bevor starting node via rosrun.

Would be nice to have a direct parameter in node for setting UDP mode.

**Comment by awesomebytes** [comment]
That seems to be pretty deep into the OpenCV backend. Exposing every possible options from the OpenCV backends (that may or not be used, for example some systems use gstreamer as backend) can be a lot of work.

I am very grateful that you posted here your workaround, though. It may help other people in the same situation. Thank you!
