### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by jake3991** [ros-drivers/video_stream_opencv#9]
I've setup this package in my catkin workspace and used the following terminal commands to compile. 
1. source /opt/ros/kinetic/setup.bash
2. catkin_make

I then try to launch the system with the following command from the launch folder of the package (I assume this is the launch file to use a usb webcam)
1. roslaunch webcam.launch

I then get the following error
raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: video_stream_opencv
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share

Any idea what's up here? I get a similar issue with all the launch files.

**Comment by k-okada** [comment]
forget to run `source devel/setup.bash`?

**Comment by jake3991** [comment]
Yeah that was exactly it, forgive the ROS newbie! Thanks for commenting back!
